# Generated by Django 4.2.26 on 2025-12-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='doctor',
        ),
    ]
