# Generated by Django 4.2.26 on 2025-11-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_appointment_price_appointment_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prior_cost',
        ),
    ]
