# Generated by Django 4.2.26 on 2025-11-29 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_appointment_prior_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
