# Generated by Django 4.2.26 on 2025-11-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_appointment_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Requires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
            ],
        ),
    ]
