# Generated by Django 4.2.26 on 2025-12-01 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_diagnosis_patient_diagnosis_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
        ),
        migrations.AlterField(
            model_name='requires',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
        ),
    ]
