# Generated by Django 4.2.26 on 2025-12-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_diagnosis_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
