# Generated by Django 4.2.26 on 2025-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_user_account_locked_until_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='default_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='default_prior_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
