# Generated by Django 4.2.26 on 2025-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_default_cost_doctor_default_prior_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Spaces are allowed.', max_length=150, unique=True),
        ),
    ]
