# Generated by Django 4.2.26 on 2025-12-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='default_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='default_prior_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
